/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CleaningRouteImport } from './routes/cleaning'
import { Route as CrewflagRouteImport } from './routes/crewflag'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InvoiceflagRouteImport } from './routes/invoiceflag'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PlumbingRouteImport } from './routes/plumbing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShippingRouteImport } from './routes/shipping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningRoute = CleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewflagRoute = CrewflagRouteImport.update({
  id: '/crewflag',
  path: '/crewflag',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceflagRoute = InvoiceflagRouteImport.update({
  id: '/invoiceflag',
  path: '/invoiceflag',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingRoute = PlumbingRouteImport.update({
  id: '/plumbing',
  path: '/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cleaning': typeof CleaningRoute
  '/crewflag': typeof CrewflagRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invoiceflag': typeof InvoiceflagRoute
  '/platform': typeof PlatformRoute
  '/plumbing': typeof PlumbingRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cleaning': typeof CleaningRoute
  '/crewflag': typeof CrewflagRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invoiceflag': typeof InvoiceflagRoute
  '/platform': typeof PlatformRoute
  '/plumbing': typeof PlumbingRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cleaning': typeof CleaningRoute
  '/crewflag': typeof CrewflagRoute
  '/how-it-works': typeof HowItWorksRoute
  '/invoiceflag': typeof InvoiceflagRoute
  '/platform': typeof PlatformRoute
  '/plumbing': typeof PlumbingRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cleaning'
    | '/crewflag'
    | '/how-it-works'
    | '/invoiceflag'
    | '/platform'
    | '/plumbing'
    | '/services'
    | '/shipping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cleaning'
    | '/crewflag'
    | '/how-it-works'
    | '/invoiceflag'
    | '/platform'
    | '/plumbing'
    | '/services'
    | '/shipping'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cleaning'
    | '/crewflag'
    | '/how-it-works'
    | '/invoiceflag'
    | '/platform'
    | '/plumbing'
    | '/services'
    | '/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CleaningRoute: typeof CleaningRoute
  CrewflagRoute: typeof CrewflagRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InvoiceflagRoute: typeof InvoiceflagRoute
  PlatformRoute: typeof PlatformRoute
  PlumbingRoute: typeof PlumbingRoute
  ServicesRoute: typeof ServicesRoute
  ShippingRoute: typeof ShippingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning': {
      id: '/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof CleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crewflag': {
      id: '/crewflag'
      path: '/crewflag'
      fullPath: '/crewflag'
      preLoaderRoute: typeof CrewflagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoiceflag': {
      id: '/invoiceflag'
      path: '/invoiceflag'
      fullPath: '/invoiceflag'
      preLoaderRoute: typeof InvoiceflagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing': {
      id: '/plumbing'
      path: '/plumbing'
      fullPath: '/plumbing'
      preLoaderRoute: typeof PlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CleaningRoute: CleaningRoute,
  CrewflagRoute: CrewflagRoute,
  HowItWorksRoute: HowItWorksRoute,
  InvoiceflagRoute: InvoiceflagRoute,
  PlatformRoute: PlatformRoute,
  PlumbingRoute: PlumbingRoute,
  ServicesRoute: ServicesRoute,
  ShippingRoute: ShippingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
